services:
  - type: web
    name: heatmap-api
    env: python
    plan: free
    pythonVersion: 3.11
    
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    
    startCommand: gunicorn heatmap_project.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: heatmap_project.settings
      - key: DEBUG
        value: false
      - key: WEATHER_API_KEY
        sync: false
      - key: ARCGIS_API_KEY
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false

