# Generated by Django 4.2.7 on 2026-02-26 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.IntegerField(blank=True, null=True)),
                ('precipitation_probability', models.IntegerField(default=0, help_text='Precipitation probability (0-100)')),
                ('precipitation', models.FloatField(default=0, help_text='Expected precipitation in mm')),
                ('cloudiness', models.IntegerField(default=0)),
                ('condition', models.CharField(choices=[('clear', 'Clear'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snowy', 'Snowy'), ('stormy', 'Stormy'), ('foggy', 'Foggy'), ('unknown', 'Unknown')], max_length=20)),
                ('condition_description', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('api_source', models.CharField(default='openweathermap', max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='weather.location')),
            ],
            options={
                'ordering': ['forecast_time'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('feels_like', models.FloatField(blank=True, help_text='Feels like temperature in Celsius', null=True)),
                ('temp_min', models.FloatField(blank=True, help_text='Minimum temperature in Celsius', null=True)),
                ('temp_max', models.FloatField(blank=True, help_text='Maximum temperature in Celsius', null=True)),
                ('humidity', models.IntegerField(help_text='Humidity percentage (0-100)')),
                ('pressure', models.IntegerField(help_text='Atmospheric pressure in hPa')),
                ('wind_speed', models.FloatField(help_text='Wind speed in m/s')),
                ('wind_direction', models.IntegerField(blank=True, help_text='Wind direction in degrees (0-360)', null=True)),
                ('precipitation', models.FloatField(default=0, help_text='Precipitation in mm')),
                ('cloudiness', models.IntegerField(default=0, help_text='Cloud coverage percentage (0-100)')),
                ('visibility', models.IntegerField(blank=True, help_text='Visibility in meters', null=True)),
                ('condition', models.CharField(choices=[('clear', 'Clear'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snowy', 'Snowy'), ('stormy', 'Stormy'), ('foggy', 'Foggy'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('condition_description', models.CharField(blank=True, max_length=255)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('api_source', models.CharField(default='openweathermap', max_length=50)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='weather.location')),
            ],
            options={
                'verbose_name_plural': 'Weather data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='weather.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='weather_loc_latitud_1f8130_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_active'], name='weather_loc_is_acti_538390_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherforecast',
            index=models.Index(fields=['location', 'forecast_time'], name='weather_wea_locatio_a5cd2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weatherforecast',
            unique_together={('location', 'forecast_time')},
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['location', '-timestamp'], name='weather_wea_locatio_4dbed4_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['is_current'], name='weather_wea_is_curr_ae69e2_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['location', 'is_active'], name='weather_wea_locatio_a4dec2_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['severity'], name='weather_wea_severit_7a4326_idx'),
        ),
    ]
